// Sprint 5 — central data dictionary. Every variable BaxterOps touches.
//
// This is THE source of truth for "what fields exist, what they mean, where they
// come from, what's manual vs computed". Drives /data-dictionary, /number-inventory,
// SourceBadge fallback when a ledger row is missing, and the covariate rubric.

export type DictCategory =
  | "rent" | "sqft" | "concession" | "occupancy" | "leasing_activity"
  | "amenity" | "utility" | "parking" | "marketing" | "conversion"
  | "subjective_covariate" | "computed_metric" | "compliance"
  | "source_verification" | "pricing_model" | "report" | "identity";

export type DictValueType = "number" | "text" | "boolean" | "currency" | "percentage" | "score" | "date" | "json";

export interface DictionaryEntry {
  key: string;
  label: string;
  category: DictCategory;
  valueType: DictValueType;
  unit?: string;
  description: string;
  usedOn: string[];
  sourceRequirement: string;
  canBeManual: boolean;
  canBeComputed: boolean;
  formula?: string;
  dependencies?: string[];
  staleAfterDays: number;
  rubric?: { type: "rating_1_5" | "boolean" | "enum"; values?: Record<string, string> };
}

const ROUTES_KEY_VALUES = ["/dashboard", "/competitors", "/comp-matching", "/reports", "/pricing-model"];

export const DATA_DICTIONARY: DictionaryEntry[] = [
  // ===== Identity =====
  { key: "address", label: "Street Address", category: "identity", valueType: "text", description: "Canonical street address of the property.", usedOn: ["/competitors","/competitors/zen-hollywood","/reports"], sourceRequirement: "Official listing or municipal record", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "phone", label: "Leasing Phone", category: "identity", valueType: "text", description: "Public-facing leasing office phone number.", usedOn: ["/competitors","/walkthrough-campaigns"], sourceRequirement: "Official site, Google Business, or RentCafe", canBeManual: true, canBeComputed: false, staleAfterDays: 180 },
  { key: "units", label: "Total Building Units", category: "identity", valueType: "number", unit: "units", description: "Total apartment count in the building.", usedOn: ["/competitors","/dashboard"], sourceRequirement: "Public listing or municipal record", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "year_built", label: "Year Built", category: "identity", valueType: "number", description: "Year the building was completed.", usedOn: ["/competitors","/comp-matching"], sourceRequirement: "LACAA, official site, or county record", canBeManual: true, canBeComputed: false, staleAfterDays: 730 },
  { key: "distance_miles", label: "Distance from Baxter (mi)", category: "identity", valueType: "number", unit: "mi", description: "Walking/driving distance from 1818 N Cherokee.", usedOn: ["/competitors","/comp-matching"], sourceRequirement: "Map/geo lookup", canBeManual: true, canBeComputed: true, formula: "haversine(baxter, competitor)", staleAfterDays: 365 },

  // ===== Rent =====
  { key: "gross_rent", label: "Gross Asking Rent", category: "rent", valueType: "currency", unit: "USD/month", description: "Posted asking rent before concession (per unit).", usedOn: ROUTES_KEY_VALUES, sourceRequirement: "Listing, call-around, or field-tour quote", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "asking_rent", label: "Asking Rent", category: "rent", valueType: "currency", unit: "USD/month", description: "Current Baxter unit asking rent.", usedOn: ["/baxter-units","/dashboard","/pricing-model"], sourceRequirement: "Internal rent roll / AppFolio", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "previous_asking_rent", label: "Previous Asking Rent", category: "rent", valueType: "currency", unit: "USD/month", description: "Last asking rent before the most recent change.", usedOn: ["/baxter-units"], sourceRequirement: "Rent roll history", canBeManual: true, canBeComputed: false, staleAfterDays: 30 },
  { key: "studio_avg_rent", label: "Studio Avg Rent", category: "rent", valueType: "currency", unit: "USD/month", description: "Mean studio rent across a competitor or set.", usedOn: ROUTES_KEY_VALUES, sourceRequirement: "Listing or call-around", canBeManual: false, canBeComputed: true, formula: "AVG of studio asking rents", dependencies: ["gross_rent"], staleAfterDays: 7 },
  { key: "1br_avg_rent", label: "1BR Avg Rent", category: "rent", valueType: "currency", unit: "USD/month", description: "Mean 1BR rent.", usedOn: ROUTES_KEY_VALUES, sourceRequirement: "Listing or call-around", canBeManual: false, canBeComputed: true, formula: "AVG(1BR rents)", dependencies: ["gross_rent"], staleAfterDays: 7 },
  { key: "2br_avg_rent", label: "2BR Avg Rent", category: "rent", valueType: "currency", unit: "USD/month", description: "Mean 2BR rent.", usedOn: ROUTES_KEY_VALUES, sourceRequirement: "Listing or call-around", canBeManual: false, canBeComputed: true, formula: "AVG(2BR rents)", dependencies: ["gross_rent"], staleAfterDays: 7 },
  { key: "rent_per_sqft", label: "$/sqft", category: "rent", valueType: "currency", unit: "USD/sqft", description: "Rent divided by square footage.", usedOn: ["/baxter-units","/dashboard","/comp-matching"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "asking_rent / square_feet", dependencies: ["asking_rent","square_feet"], staleAfterDays: 7 },
  { key: "net_effective_rent", label: "Net Effective Rent", category: "computed_metric", valueType: "currency", unit: "USD/month", description: "Rent net of free-month concessions amortized over the lease term.", usedOn: ["/comp-matching","/pricing-model","/reports"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "((gross_rent * (lease_months - free_months)) - extra_credit) / lease_months", dependencies: ["gross_rent","lease_months","free_months","look_and_lease_bonus"], staleAfterDays: 7 },
  { key: "predicted_rent", label: "Predicted Market Rent", category: "pricing_model", valueType: "currency", unit: "USD/month", description: "Pricing model's predicted market rent for a Baxter unit.", usedOn: ["/pricing-model","/baxter-units"], sourceRequirement: "Computed from matched comps + covariate adjustments", canBeManual: false, canBeComputed: true, formula: "AVG(top5_matched_comp_avg_rent) + Σ covariate_adjustments", dependencies: ["gross_rent","walk_in_closet","bedroom_window","patio","den","corner_unit","natural_light","floor"], staleAfterDays: 14 },
  { key: "rent_gap", label: "Rent Gap vs Comps", category: "computed_metric", valueType: "currency", unit: "USD", description: "Difference between Baxter rent and matched-comp average.", usedOn: ["/comp-matching","/reports"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "baxter_rent - matched_comp_avg_rent", dependencies: ["asking_rent","matched_comp_avg_rent"], staleAfterDays: 7 },

  // ===== Square footage =====
  { key: "square_feet", label: "Square Feet", category: "sqft", valueType: "number", unit: "sqft", description: "Unit floor area.", usedOn: ROUTES_KEY_VALUES, sourceRequirement: "Listing, floorplan PDF, or field-tour measurement", canBeManual: true, canBeComputed: false, staleAfterDays: 180 },
  { key: "studio_avg_sqft", label: "Studio Avg Sqft", category: "sqft", valueType: "number", unit: "sqft", description: "Mean studio sqft.", usedOn: ["/competitors","/dashboard"], sourceRequirement: "Listing", canBeManual: false, canBeComputed: true, formula: "AVG(studio_square_feet)", dependencies: ["square_feet"], staleAfterDays: 180 },
  { key: "1br_avg_sqft", label: "1BR Avg Sqft", category: "sqft", valueType: "number", unit: "sqft", description: "Mean 1BR sqft.", usedOn: ["/competitors","/dashboard"], sourceRequirement: "Listing", canBeManual: false, canBeComputed: true, formula: "AVG(1BR square_feet)", dependencies: ["square_feet"], staleAfterDays: 180 },
  { key: "2br_avg_sqft", label: "2BR Avg Sqft", category: "sqft", valueType: "number", unit: "sqft", description: "Mean 2BR sqft.", usedOn: ["/competitors","/dashboard"], sourceRequirement: "Listing", canBeManual: false, canBeComputed: true, formula: "AVG(2BR square_feet)", dependencies: ["square_feet"], staleAfterDays: 180 },

  // ===== Concessions =====
  { key: "free_months", label: "Free Rent Months", category: "concession", valueType: "number", unit: "months", description: "Free months built into the standard concession.", usedOn: ["/comp-matching","/competitors","/walkthrough-campaigns"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "free_rent_weeks", label: "Free Rent Weeks", category: "concession", valueType: "number", unit: "weeks", description: "Free weeks if advertised in weeks not months.", usedOn: ["/competitors"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "lease_months", label: "Required Lease Term (months)", category: "concession", valueType: "number", unit: "months", description: "Lease length the concession requires.", usedOn: ["/comp-matching","/pricing-model"], sourceRequirement: "Live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 30 },
  { key: "look_and_lease_bonus", label: "Look-and-Lease Bonus", category: "concession", valueType: "currency", unit: "USD", description: "One-time credit for signing within a window.", usedOn: ["/comp-matching","/competitors"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "look_and_lease_window_hours", label: "Look-and-Lease Window", category: "concession", valueType: "number", unit: "hours", description: "Window during which the LAL credit applies.", usedOn: ["/comp-matching"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "specials", label: "Specials / Concession Text", category: "concession", valueType: "text", description: "Free-form concession statement.", usedOn: ["/competitors","/reports"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "concession_value_total", label: "Total Concession Value", category: "computed_metric", valueType: "currency", unit: "USD", description: "Free rent + LAL aggregated over the lease term.", usedOn: ["/comp-matching"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "(gross_rent * free_months) + look_and_lease_bonus", dependencies: ["gross_rent","free_months","look_and_lease_bonus"], staleAfterDays: 7 },
  { key: "deposit", label: "Security Deposit", category: "concession", valueType: "currency", unit: "USD", description: "Required security deposit.", usedOn: ["/competitors","/baxter-units"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 30 },

  // ===== Occupancy + leasing activity =====
  { key: "occupancy_pct", label: "Occupancy %", category: "occupancy", valueType: "percentage", unit: "%", description: "Currently occupied units / total units.", usedOn: ["/dashboard","/competitors","/reports"], sourceRequirement: "Internal rent roll or call-around", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "leased_pct", label: "Leased %", category: "occupancy", valueType: "percentage", unit: "%", description: "Signed leases + occupied / total. Leading indicator.", usedOn: ["/dashboard","/competitors","/reports"], sourceRequirement: "Internal rent roll or call-around", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "tours_last_week", label: "Tours Last Week", category: "leasing_activity", valueType: "number", unit: "tours", description: "Total in-person + virtual tours last week.", usedOn: ["/dashboard","/competitors","/reports"], sourceRequirement: "Call-around or AppFolio", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "leases_last_week", label: "Leases Last Week", category: "leasing_activity", valueType: "number", unit: "leases", description: "Leases signed last week.", usedOn: ["/dashboard","/competitors","/reports"], sourceRequirement: "Call-around or AppFolio", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "days_vacant", label: "Days Vacant", category: "leasing_activity", valueType: "number", unit: "days", description: "Consecutive days a unit has been vacant.", usedOn: ["/baxter-units","/dashboard"], sourceRequirement: "Computed from rent roll", canBeManual: false, canBeComputed: true, formula: "today - vacant_since", dependencies: ["vacant_since"], staleAfterDays: 1 },
  { key: "vacancy_loss", label: "Monthly Vacancy Loss", category: "computed_metric", valueType: "currency", unit: "USD/month", description: "Sum of asking rents on vacant units.", usedOn: ["/dashboard","/reports"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "SUM(asking_rent WHERE occupancy = vacant)", dependencies: ["asking_rent"], staleAfterDays: 7 },

  // ===== Amenity + utility + parking =====
  { key: "parking_included", label: "Parking Included", category: "parking", valueType: "boolean", description: "Whether parking is included in rent.", usedOn: ["/competitors","/comp-matching"], sourceRequirement: "Listing or field-tour quote", canBeManual: true, canBeComputed: false, staleAfterDays: 90 },
  { key: "valet_included", label: "Valet Included", category: "parking", valueType: "boolean", description: "Whether valet parking is included.", usedOn: ["/competitors","/comp-matching"], sourceRequirement: "Listing or field-tour quote", canBeManual: true, canBeComputed: false, staleAfterDays: 90 },
  { key: "parking_spots_included", label: "Parking Spots Included", category: "parking", valueType: "number", description: "Number of included parking spots per unit.", usedOn: ["/competitors","/comp-matching"], sourceRequirement: "Live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 90 },
  { key: "water_included", label: "Water Included", category: "utility", valueType: "boolean", description: "Whether water is included in rent.", usedOn: ["/competitors","/comp-matching","/utility-allowance"], sourceRequirement: "Lease addendum or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 180 },
  { key: "power_included", label: "Electricity Included", category: "utility", valueType: "boolean", description: "Whether electricity is included in rent.", usedOn: ["/competitors","/utility-allowance"], sourceRequirement: "Lease addendum or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 180 },
  { key: "gas_included", label: "Gas Included", category: "utility", valueType: "boolean", description: "Whether gas is included in rent.", usedOn: ["/competitors","/utility-allowance"], sourceRequirement: "Lease addendum or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 180 },
  { key: "internet_included", label: "Internet Included", category: "utility", valueType: "boolean", description: "Whether internet is included in rent.", usedOn: ["/competitors"], sourceRequirement: "Listing or live quote", canBeManual: true, canBeComputed: false, staleAfterDays: 180 },
  { key: "in_unit_laundry", label: "In-Unit Laundry", category: "utility", valueType: "boolean", description: "Whether the unit has washer/dryer.", usedOn: ["/competitors","/comp-matching","/photos-amenities"], sourceRequirement: "Listing or field-tour photo", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "balcony_or_patio", label: "Balcony / Patio", category: "amenity", valueType: "boolean", description: "Private outdoor space on the unit.", usedOn: ["/competitors","/baxter-units","/photos-amenities"], sourceRequirement: "Listing or field-tour photo", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "bedroom_window", label: "Bedroom Has Window", category: "amenity", valueType: "boolean", description: "Whether the bedroom has a window (legal-defining covariate).", usedOn: ["/baxter-units","/pricing-model"], sourceRequirement: "Field-tour observation or floorplan", canBeManual: true, canBeComputed: false, staleAfterDays: 730 },
  { key: "walk_in_closet", label: "Walk-in Closet Rating", category: "amenity", valueType: "score", unit: "0-5", description: "Quality of walk-in closet, 0–5.", usedOn: ["/baxter-units","/pricing-model"], sourceRequirement: "Field-tour rating", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "smart_thermostat", label: "Smart Thermostat", category: "amenity", valueType: "boolean", description: "Whether the unit has a smart thermostat.", usedOn: ["/competitors"], sourceRequirement: "Field-tour photo or listing", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },

  // ===== Marketing + conversion =====
  { key: "monthly_marketing_spend", label: "Monthly Marketing Spend", category: "marketing", valueType: "currency", unit: "USD/month", description: "Monthly spend per marketing channel.", usedOn: ["/marketing-roi","/dashboard","/reports"], sourceRequirement: "Invoice or contract", canBeManual: true, canBeComputed: false, staleAfterDays: 30 },
  { key: "lead_count", label: "Lead Count", category: "marketing", valueType: "number", unit: "leads", description: "Inbound leads per channel per period.", usedOn: ["/marketing-roi","/dashboard","/lead-funnel"], sourceRequirement: "AppFolio or channel report", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "tour_count", label: "Tour Count", category: "conversion", valueType: "number", unit: "tours", description: "Tours scheduled and completed.", usedOn: ["/marketing-roi","/lead-funnel"], sourceRequirement: "AppFolio", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "application_count", label: "Application Count", category: "conversion", valueType: "number", unit: "applications", description: "Submitted applications.", usedOn: ["/marketing-roi","/lead-funnel"], sourceRequirement: "AppFolio", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "lease_count", label: "Lease Count", category: "conversion", valueType: "number", unit: "leases", description: "Signed leases.", usedOn: ["/marketing-roi","/lead-funnel","/dashboard"], sourceRequirement: "AppFolio", canBeManual: true, canBeComputed: false, staleAfterDays: 7 },
  { key: "cost_per_lead", label: "Cost per Lead", category: "computed_metric", valueType: "currency", unit: "USD/lead", description: "Monthly channel spend divided by leads.", usedOn: ["/marketing-roi"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "monthly_marketing_spend / lead_count", dependencies: ["monthly_marketing_spend","lead_count"], staleAfterDays: 7 },
  { key: "cost_per_tour", label: "Cost per Tour", category: "computed_metric", valueType: "currency", unit: "USD/tour", description: "Channel spend divided by tours.", usedOn: ["/marketing-roi"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "monthly_marketing_spend / tour_count", dependencies: ["monthly_marketing_spend","tour_count"], staleAfterDays: 7 },
  { key: "cost_per_lease", label: "Cost per Lease", category: "computed_metric", valueType: "currency", unit: "USD/lease", description: "Channel spend divided by leases.", usedOn: ["/marketing-roi"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "monthly_marketing_spend / lease_count", dependencies: ["monthly_marketing_spend","lease_count"], staleAfterDays: 7 },

  // ===== Subjective covariates (manual only) =====
  { key: "tour_booking_ease", label: "Ease of Booking Tour", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "How easy it was to schedule the tour.", usedOn: ["/walkthrough-campaigns","/comp-matching","/competitors"], sourceRequirement: "Manual user entry — field tour only", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "Difficult — failed attempts", "2": "Slow / friction", "3": "Average", "4": "Easy and clear", "5": "Instant / no friction" } } },
  { key: "response_speed_hours", label: "Response Speed (hours)", category: "subjective_covariate", valueType: "number", unit: "hours", description: "How long the leasing office took to respond.", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90 },
  { key: "kindness", label: "Leasing Agent Kindness", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Warmth and helpfulness of leasing agent.", usedOn: ["/walkthrough-campaigns","/comp-matching"], sourceRequirement: "Manual user entry — field tour only", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "Rude/dismissive", "2": "Cold/minimal", "3": "Neutral", "4": "Warm/helpful", "5": "Exceptionally welcoming" } } },
  { key: "professionalism", label: "Leasing Agent Professionalism", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "How polished, prepared, and knowledgeable the agent was.", usedOn: ["/walkthrough-campaigns","/comp-matching"], sourceRequirement: "Manual user entry — field tour only", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "Disorganized", "2": "Unprepared", "3": "Adequate", "4": "Polished", "5": "Highly polished, knowledgeable" } } },
  { key: "cleanliness", label: "Building Cleanliness", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Overall cleanliness rating.", usedOn: ["/walkthrough-campaigns","/comp-matching"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "Dirty", "2": "Noticeable issues", "3": "Acceptable", "4": "Clean", "5": "Spotless / premium" } } },
  { key: "drinks_or_snacks_offered", label: "Drinks/Snacks Offered", category: "subjective_covariate", valueType: "boolean", description: "Did the leasing office offer drinks or snacks during the tour?", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry — field tour only", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "boolean" } },
  { key: "amenity_quality", label: "Amenity Quality", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Overall amenity package quality.", usedOn: ["/walkthrough-campaigns","/comp-matching"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "Weak", "2": "Below average", "3": "Normal", "4": "Strong", "5": "Exceptional" } } },
  { key: "unit_quality", label: "Unit Quality", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Overall unit quality rating.", usedOn: ["/walkthrough-campaigns","/comp-matching"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5" } },
  { key: "common_area_quality", label: "Common Area Quality", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Overall common area quality.", usedOn: ["/walkthrough-campaigns","/comp-matching"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5" } },
  { key: "closing_strength", label: "Closing Strength", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "How well the agent closed the tour.", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "No clear next step", "2": "Weak follow-up", "3": "Normal", "4": "Strong next-step guidance", "5": "Excellent close, clear urgency" } } },
  { key: "desperation_vs_confidence", label: "Desperation → Confidence (5=confident)", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "5 = leasing office is confident and not pressured to sign.", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5" } },
  { key: "pressure_level", label: "Sales Pressure Level", category: "subjective_covariate", valueType: "text", description: "Low / medium / high pressure during the tour.", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "enum", values: { low: "low", medium: "medium", high: "high" } } },
  { key: "hidden_concession_offered", label: "Hidden Concession Offered", category: "subjective_covariate", valueType: "boolean", description: "Did the leasing office reveal a concession not advertised online?", usedOn: ["/walkthrough-campaigns","/reports"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "boolean" } },
  { key: "parking_deal_offered", label: "Parking Deal Offered", category: "subjective_covariate", valueType: "boolean", description: "Was a parking concession verbally offered?", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "boolean" } },
  { key: "fees_waivable", label: "Fees Waivable", category: "subjective_covariate", valueType: "boolean", description: "Did the office indicate application/admin fees could be waived?", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "boolean" } },
  { key: "follow_up_quality", label: "Follow-up Quality", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Quality of post-tour follow-up.", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5", values: { "1": "None", "2": "Weak", "3": "Normal", "4": "Strong", "5": "Excellent" } } },
  { key: "would_renter_choose_over_baxter", label: "Would Renter Choose Over Baxter?", category: "subjective_covariate", valueType: "boolean", description: "Honest assessment: would a real renter pick this competitor over Baxter?", usedOn: ["/walkthrough-campaigns","/reports","/competitors"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "boolean" } },
  { key: "tour_quality", label: "Overall Tour Quality", category: "subjective_covariate", valueType: "score", unit: "1-5", description: "Overall quality of the tour experience.", usedOn: ["/walkthrough-campaigns"], sourceRequirement: "Manual user entry", canBeManual: true, canBeComputed: false, staleAfterDays: 90, rubric: { type: "rating_1_5" } },

  // ===== Computed scores =====
  { key: "comp_quality_score", label: "Comp Quality Score (0-100)", category: "computed_metric", valueType: "score", unit: "0-100", description: "Weighted similarity score combining distance, sqft, amenities, etc.", usedOn: ["/competitors","/comp-matching"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "weighted(bedroom_match, sqft_similarity, distance, amenities, building_class, concessions, qualitative)", dependencies: ["square_feet","distance_miles","amenity_quality"], staleAfterDays: 30 },
  { key: "threat_level", label: "Threat Level (1-5)", category: "computed_metric", valueType: "score", unit: "1-5", description: "Subjective threat score combining comp quality + activity + concessions.", usedOn: ["/competitors","/dashboard"], sourceRequirement: "Manual + computed", canBeManual: true, canBeComputed: true, formula: "f(comp_quality_score, lease_velocity, concession_strength)", dependencies: ["comp_quality_score","leases_last_week","free_rent_weeks"], staleAfterDays: 14 },
  { key: "composite_experience_score", label: "Composite Tour Experience Score", category: "computed_metric", valueType: "score", unit: "1-5", description: "Weighted average of 8-9 manual covariate scores.", usedOn: ["/walkthrough-campaigns","/competitors","/reports"], sourceRequirement: "Computed from manual covariate scores", canBeManual: false, canBeComputed: true, formula: "0.10*tour_booking_ease + 0.10*kindness + 0.10*professionalism + 0.15*cleanliness + 0.15*amenity_quality + 0.15*unit_quality + 0.10*common_area_quality + 0.10*closing_strength + 0.05*follow_up_quality", dependencies: ["tour_booking_ease","kindness","professionalism","cleanliness","amenity_quality","unit_quality","common_area_quality","closing_strength","follow_up_quality"], staleAfterDays: 90 },

  // ===== Compliance =====
  { key: "tenant_rent_portion", label: "Tenant Rent Portion", category: "compliance", valueType: "currency", unit: "USD/month", description: "Tenant's share of monthly rent under affordable program.", usedOn: ["/tenant-outreach","/utility-allowance","/recertification"], sourceRequirement: "Income certification packet", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "subsidy_portion", label: "Subsidy Portion", category: "compliance", valueType: "currency", unit: "USD/month", description: "Subsidy-provider share of monthly rent.", usedOn: ["/utility-allowance","/recertification"], sourceRequirement: "HAP contract", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "utility_allowance", label: "Utility Allowance", category: "compliance", valueType: "currency", unit: "USD/month", description: "LAHD utility allowance for the unit type.", usedOn: ["/utility-allowance","/recertification"], sourceRequirement: "LAHD utility allowance schedule", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "lahd_max_allowed", label: "LAHD Max Allowed (rent + allowance)", category: "compliance", valueType: "currency", unit: "USD/month", description: "LAHD covenant cap on tenant rent plus allowance.", usedOn: ["/utility-allowance"], sourceRequirement: "LAHD covenant", canBeManual: true, canBeComputed: false, staleAfterDays: 365 },
  { key: "tenant_burden", label: "Tenant Burden (rent + allowance)", category: "computed_metric", valueType: "currency", unit: "USD/month", description: "Computed sum of tenant rent + utility allowance.", usedOn: ["/utility-allowance"], sourceRequirement: "Computed", canBeManual: false, canBeComputed: true, formula: "tenant_rent_portion + utility_allowance", dependencies: ["tenant_rent_portion","utility_allowance"], staleAfterDays: 365 },
];

// Helper lookup
export function getDictionaryEntry(key: string): DictionaryEntry | undefined {
  return DATA_DICTIONARY.find(e => e.key === key);
}
