// Seed data from:
//   - Weekly Lease Up Report / Call Around dated 2026-05-26 (Baxter market comp)
//   - SGD property mgmt meeting transcript
//
// All competitor metrics are call-around snapshots and should be refreshed weekly.

import type {
  BaxterUnit,
  CompetitorProperty,
  Lead,
  LocalPartnership,
  MarketingSource,
  MatchingWeights,
  Property,
  Task,
  Tenant,
  WalkthroughTour,
} from "./types";

export const BAXTER: Property = {
  id: "baxter",
  name: "The Baxter Hollywood",
  address: "1818 N Cherokee Ave, Los Angeles, CA 90028",
  phone: "844-642-8958",
  website: "https://thebaxterhollywood.com/",
  units: 86,
  isBaxter: true,
};

// --- Baxter units (seeded from meeting transcript) ---
export const BAXTER_UNITS: BaxterUnit[] = [
  {
    id: "u-105",
    unitNumber: "105",
    floor: 1,
    type: "2BR",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    askingRent: 2499,
    previousAskingRent: 2775,
    concession: "1 month free on 13-month lease",
    concessionDescription: "1 month free on a 13-month lease — loss leader to drive traffic.",
    freeMonths: 1,
    leaseMonths: 13,
    leaseTermMonths: 13,
    deposit: 1000,
    parkingIncluded: false,
    occupancy: "vacant",
    program: "conventional",
    daysVacant: 21,
    dataQualityFlags: ["fq-unit-105-concession"],
    pricingHistory: [
      {
        oldRent: 2775,
        newRent: 2499,
        reason: "Loss-leader repricing to drive traffic (per meeting transcript).",
        changedAt: "2026-05-01",
        changedBy: "Lucas",
      },
    ],
    covariates: {
      patio: true,
      sideYard: true,
      den: true,
      bedroomWindow: true,
      naturalLight: 4,
      walkInCloset: 3,
      finishQuality: 4,
      layoutQuality: 4,
    },
    strengths: ["patio", "side yard", "den", "ground floor with private entry"],
    weaknesses: ["ground floor noise exposure"],
    suggestedAction: "Loss leader — keep aggressive pricing to drive traffic",
    confidence: 70,
    notes: "Original Baxter resident loved this layout. Strong differentiation if shown in person.",
  },
  {
    id: "u-301",
    unitNumber: "301",
    floor: 3,
    type: "1BR",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 820,
    askingRent: 2799,
    previousAskingRent: 2899,
    notes: "Per Lucas: the unit everyone wants once they see it. Asking rent corrected to $2,799 to match Bailey's uploaded note. Verify against live listing before final owner report.",
    pricingHistory: [
      {
        oldRent: 2899,
        newRent: 2799,
        reason: "Bailey uploaded note indicated Baxter 301 $2,799 1BR, big walk-in closet.",
        changedAt: "2026-05-26",
        changedBy: "Bailey / Claude Code Sprint 2",
      },
    ],
    dataQualityFlags: ["fq-unit-301-rent"],
    occupancy: "vacant",
    program: "conventional",
    daysVacant: 18,
    covariates: {
      bedroomWindow: true,
      patio: true,
      walkInCloset: 5,
      naturalLight: 5,
      viewQuality: 4,
      finishQuality: 4,
      layoutQuality: 5,
      streetFacing: true,
    },
    strengths: ["front-facing", "huge walk-in closet", "patio", "street view"],
    weaknesses: ["street noise"],
    suggestedAction: "Premium upsell — drive traffic with cheaper units, close on this one",
    confidence: 85,
  },
  {
    id: "u-306",
    unitNumber: "306",
    floor: 3,
    type: "1BR",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 760,
    askingRent: 2599,
    previousAskingRent: 3060,
    occupancy: "vacant",
    program: "conventional",
    daysVacant: 35,
    covariates: {
      bedroomWindow: true,
      naturalLight: 3,
      walkInCloset: 3,
      finishQuality: 3,
      layoutQuality: 3,
    },
    strengths: ["fair light", "standard 1BR layout"],
    weaknesses: ["no patio", "interior position"],
    suggestedAction: "Hold at $2,599 — closer to matched comp average",
    confidence: 65,
  },
  {
    id: "u-308",
    unitNumber: "308",
    floor: 3,
    type: "1BR",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    askingRent: 2599,
    previousAskingRent: 3080,
    occupancy: "vacant",
    program: "conventional",
    daysVacant: 42,
    covariates: {
      bedroomWindow: false,
      naturalLight: 2,
      walkInCloset: 2,
      finishQuality: 3,
      layoutQuality: 2,
    },
    strengths: ["lowest entry price for 1BR"],
    weaknesses: ["NO BEDROOM WINDOW — major negative covariate"],
    suggestedAction: "Show last. Price below 1BR comp avg. Lead with concession.",
    confidence: 80,
    notes: "No-window unit. Must price below stronger 1BR comps to clear.",
  },
  {
    id: "u-312",
    unitNumber: "312",
    floor: 3,
    type: "1BR",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 775,
    askingRent: 2699,
    occupancy: "vacant",
    program: "conventional",
    daysVacant: 28,
    covariates: {
      bedroomWindow: true,
      cornerUnit: true,
      naturalLight: 4,
      viewQuality: 3,
      walkInCloset: 3,
      finishQuality: 3,
      layoutQuality: 4,
    },
    strengths: ["corner unit", "extra light", "slightly better view than 308"],
    weaknesses: ["not as marquee as 301"],
    suggestedAction: "Hold as a step-up from 306/308",
    confidence: 70,
  },
];

// --- Verification defaults applied to all competitors ---
// All competitor metrics came from the 2026-05-26 call-around (uploaded comp report).
// Verification URLs are intentionally blank — Bailey must add them, not Claude.
const COMP_VERIFICATION_OVERRIDES: Record<string, Partial<CompetitorProperty>> = {
  "c-camden": { dataQualityFlags: ["fq-camden-2br-sqft"], dataConfidence: "low" },
  "c-ava-hollywood": { dataQualityFlags: ["fq-ava-2br-sqft"], dataConfidence: "low" },
  "c-encore": { dataQualityFlags: ["fq-encore-1br-sqft"], dataConfidence: "low" },
  "c-1600-vine": { dataQualityFlags: ["fq-1600-vine-address"], dataConfidence: "low" },
  "c-ardence-bloom": { dataQualityFlags: ["fq-ardence-2br-rent"], dataConfidence: "medium" },
  "c-archer-hollywood": { dataQualityFlags: ["fq-archer-zip"], dataConfidence: "medium" },
  "c-zen-hollywood": {
    dataConfidence: "high",
    lastVerifiedAt: "2026-05-26",
    verifiedBy: "Bailey (field tour)",
    dataQualityFlags: [
      "fq-zen-address","fq-zen-19m-applicability","fq-zen-424",
      "fq-zen-630-sqft","fq-zen-2f-unit","fq-zen-gym-photo",
      "fq-zen-movein-cost","fq-zen-fees-waivable","fq-zen-source-merging",
    ],
  },
  "c-jardine": {
    sourceType: "field_tour",
    dataConfidence: "high",
    lastVerifiedAt: "2026-05-27",
    verifiedBy: "Bailey (field tour)",
    dataQualityFlags: [
      "fq-jardine-504-availability","fq-jardine-501-availability",
      "fq-jardine-pest-fee","fq-jardine-other-monthly-fee",
      "fq-jardine-theater-rental","fq-jardine-clubhouse-rental",
      "fq-jardine-listing-verify","fq-jardine-not-comparable",
      "fq-jardine-prices-daily-change",
    ],
  },
  "c-highland": {
    sourceType: "field_tour",
    dataConfidence: "high",
    lastVerifiedAt: "2026-05-27",
    verifiedBy: "Bailey (field tour)",
    dataQualityFlags: [
      "fq-highland-1br-unit-number","fq-highland-2br-unit-number",
      "fq-highland-2br-vs-402","fq-highland-utility-billing",
      "fq-highland-concession-applicability","fq-highland-listing-verify",
    ],
  },
  "c-vine-1600": {
    sourceType: "field_tour",
    dataConfidence: "high",
    lastVerifiedAt: "2026-05-27",
    verifiedBy: "Bailey (field tour)",
    dataQualityFlags: [
      "fq-vine-address","fq-vine-unit-number","fq-vine-utility-cost",
      "fq-vine-parking-cost","fq-vine-listing-verify",
    ],
  },
};

function withVerificationDefaults(comp: CompetitorProperty): CompetitorProperty {
  const overrides = COMP_VERIFICATION_OVERRIDES[comp.id] ?? {};
  return {
    sourceType: "uploaded_market_comp_report",
    dataConfidence: "medium",
    lastVerifiedAt: "2026-05-26",
    verifiedBy: "Lucas (call-around)",
    ...comp,
    ...overrides,
  };
}

// --- Hollywood competitor properties (from market comp 2026-05-26) ---
const RAW_COMPETITORS: CompetitorProperty[] = [
  {
    id: "c-line-lofts",
    name: "The Line Lofts",
    address: "1737 N Las Palmas, LA 90028",
    phone: "323.573.9378",
    units: 82,
    distanceMiles: 0.1,
    occupancyPct: 95,
    leasedPct: 95,
    toursLastWeek: 0,
    leasesLastWeek: 2,
    deposit: "$750",
    specials: "1st month free on select units",
    freeRentWeeks: 4,
    amenities: ["rooftop", "gym", "lounge", "package room"],
    threatLevel: 4,
    compQualityScore: 78,
    unitTypes: [
      { type: "studio", minRent: 2350, maxRent: 2895, avgRent: 2623, minSqft: 415, maxSqft: 743, avgSqft: 579 },
      { type: "1BR", minRent: 3250, maxRent: 3300, avgRent: 3275, minSqft: 859, maxSqft: 859, avgSqft: 859 },
      { type: "2BR", minRent: 3800, maxRent: 5300, avgRent: 4550, minSqft: 1084, maxSqft: 1275, avgSqft: 1180 },
    ],
    notes: "Max rates include furnished pricing. Closest geographically.",
  },
  {
    id: "c-jefferson-highland",
    name: "Jefferson Highland",
    address: "1724 N. Highland, LA 90028",
    phone: "323.469.4000",
    units: 270,
    distanceMiles: 0.3,
    occupancyPct: 96,
    leasedPct: 96,
    toursLastWeek: 6,
    leasesLastWeek: 1,
    deposit: "$800",
    specials: "2 Weeks Free + $500 Visa Gift Card",
    freeRentWeeks: 2,
    lookAndLeaseBonus: 500,
    amenities: ["rooftop", "pool", "gym", "lounge", "coworking", "parking"],
    threatLevel: 5,
    compQualityScore: 82,
    unitTypes: [
      { type: "1BR", avgRent: 2249, minSqft: 719, maxSqft: 737, avgSqft: 728 },
      { type: "2BR", minRent: 2995, maxRent: 3301, avgRent: 3148, minSqft: 1064, maxSqft: 1117, avgSqft: 1091 },
    ],
    notes: "Aggressive lease-up specials. Strong amenity stack.",
  },
  {
    id: "c-1600-vine",
    name: "1600 Vine Avenue",
    address: "1411 N. Highland Ave., LA 90028",
    phone: "323-741-6667",
    units: 76,
    distanceMiles: 0.4,
    occupancyPct: 92,
    leasedPct: 92,
    toursLastWeek: 5,
    leasesLastWeek: 0,
    deposit: "$1,500",
    specials: "6 Weeks Free",
    freeRentWeeks: 6,
    amenities: ["rooftop", "lounge", "gym"],
    threatLevel: 4,
    compQualityScore: 75,
    unitTypes: [
      { type: "studio", minRent: 2241, maxRent: 2556, avgRent: 2399, minSqft: 976, maxSqft: 976, avgSqft: 976 },
      { type: "1BR", minRent: 2870, maxRent: 2899, avgRent: 2885, minSqft: 733, maxSqft: 1323, avgSqft: 1028 },
      { type: "2BR", minRent: 3599, maxRent: 4362, avgRent: 3981, minSqft: 998, maxSqft: 998, avgSqft: 998 },
    ],
  },
  {
    id: "c-camden",
    name: "The Camden",
    address: "1600 Vine, LA 90028",
    phone: "323.462.0400",
    units: 375,
    distanceMiles: 0.4,
    occupancyPct: 96,
    leasedPct: 96,
    toursLastWeek: 0,
    leasesLastWeek: 0,
    deposit: "$500-$1000",
    specials: "8 Weeks Free + $1000 look-and-lease",
    freeRentWeeks: 8,
    lookAndLeaseBonus: 1000,
    amenities: ["rooftop", "pool", "gym", "lounge", "coworking", "parking", "package room"],
    threatLevel: 5,
    compQualityScore: 86,
    unitTypes: [
      { type: "studio", minRent: 2901, maxRent: 3181, avgRent: 3041, minSqft: 541, maxSqft: 541, avgSqft: 541 },
      { type: "1BR", minRent: 3003, maxRent: 4325, avgRent: 3664, minSqft: 759, maxSqft: 759, avgSqft: 759 },
      { type: "2BR", minRent: 3789, maxRent: 5492, avgRent: 4641, minSqft: 1051, maxSqft: 5492, avgSqft: 3272 },
    ],
    notes: "Major competitor. Largest free-rent concession on the market.",
  },
  {
    id: "c-fusion",
    name: "Fusion",
    address: "1619 N. La Brea Ave., LA 90028",
    phone: "323.876.1619",
    units: 180,
    distanceMiles: 0.5,
    occupancyPct: 91,
    leasedPct: 91,
    toursLastWeek: 1,
    leasesLastWeek: 0,
    deposit: "$750/$1000/$1500",
    specials: "6 weeks free + $1000 look and lease",
    freeRentWeeks: 6,
    lookAndLeaseBonus: 1000,
    amenities: ["rooftop", "gym", "lounge"],
    threatLevel: 4,
    compQualityScore: 79,
    unitTypes: [
      { type: "studio", minRent: 2683, maxRent: 3039, avgRent: 2861, minSqft: 907, maxSqft: 973, avgSqft: 940 },
      { type: "1BR", minRent: 2966, maxRent: 3446, avgRent: 3206, minSqft: 773, maxSqft: 1190, avgSqft: 982 },
      { type: "2BR", minRent: 3757, maxRent: 4552, avgRent: 4042, minSqft: 1240, maxSqft: 1453, avgSqft: 1347 },
    ],
  },
  {
    id: "c-encore",
    name: "Encore",
    address: "1540 N. Vine, LA 90028",
    phone: "323.469.4663",
    units: 287,
    distanceMiles: 0.6,
    occupancyPct: 94,
    leasedPct: 94,
    deposit: "$500",
    amenities: ["rooftop", "pool", "gym", "lounge", "parking"],
    threatLevel: 3,
    compQualityScore: 72,
    unitTypes: [
      { type: "studio", minRent: 2189, maxRent: 2369, avgRent: 2279, minSqft: 846, maxSqft: 846, avgSqft: 846 },
      { type: "1BR", minRent: 2359, maxRent: 2989, avgRent: 2674, minSqft: 579, maxSqft: 2819, avgSqft: 1699 },
      { type: "2BR", minRent: 3669, maxRent: 6229, avgRent: 4949, minSqft: 1104, maxSqft: 1191, avgSqft: 1148 },
    ],
    notes: "No-answer on call-around — refresh next week.",
  },
  {
    id: "c-argyle-house",
    name: "Argyle House",
    address: "1714 N. McCadden Pl, LA 90028",
    phone: "323.871.4041 ext 3",
    units: 218,
    distanceMiles: 0.3,
    occupancyPct: 93,
    leasedPct: 96,
    deposit: "750/1500",
    specials: "Reduced rates",
    amenities: ["rooftop", "gym", "lounge", "parking"],
    threatLevel: 3,
    compQualityScore: 74,
    unitTypes: [
      { type: "1BR", minRent: 2549, maxRent: 2579, avgRent: 2564, minSqft: 585, maxSqft: 819, avgSqft: 702 },
      { type: "2BR", minRent: 3349, maxRent: 4182, avgRent: 3766, minSqft: 1136, maxSqft: 1410, avgSqft: 1273 },
    ],
  },
  {
    id: "c-arrive-hollywood",
    name: "Arrive Hollywood",
    address: "1755 Argyle Ave., LA 90028",
    phone: "323.603.0331",
    units: 114,
    distanceMiles: 0.4,
    occupancyPct: 94,
    leasedPct: 94,
    toursLastWeek: 0,
    leasesLastWeek: 2,
    deposit: "$1,000",
    specials: "1 Month Free",
    freeRentWeeks: 4,
    amenities: ["rooftop", "lounge", "gym"],
    threatLevel: 3,
    compQualityScore: 71,
    unitTypes: [
      { type: "studio", minRent: 3060, maxRent: 3170, avgRent: 3115, minSqft: 751, maxSqft: 751, avgSqft: 751 },
      { type: "1BR", minRent: 4000, maxRent: 4000, avgRent: 4000 },
      { type: "2BR", minRent: 5823, maxRent: 6800, avgRent: 6312 },
    ],
  },
  {
    id: "c-el-centro",
    name: "El Centro",
    address: "6201 Hollywood Blvd., LA 90028",
    phone: "323.745.2488",
    units: 535,
    distanceMiles: 0.8,
    occupancyPct: 92,
    leasedPct: 95,
    deposit: "$500",
    specials: "2 weeks free",
    freeRentWeeks: 2,
    amenities: ["rooftop", "pool", "gym", "lounge"],
    threatLevel: 3,
    compQualityScore: 68,
    unitTypes: [
      { type: "studio", minRent: 2199, maxRent: 2445, avgRent: 2322, minSqft: 571, maxSqft: 740, avgSqft: 656 },
      { type: "1BR", minRent: 2019, maxRent: 2919, avgRent: 2469, minSqft: 660, maxSqft: 786, avgSqft: 723 },
      { type: "2BR", minRent: 3539, maxRent: 3955, avgRent: 3747, minSqft: 1036, maxSqft: 1216, avgSqft: 1126 },
    ],
  },
  {
    id: "c-modera-hollywood",
    name: "Modera Hollywood",
    address: "6200 Hollywood Blvd, LA 90028",
    phone: "323.745.1899",
    units: 507,
    distanceMiles: 0.8,
    occupancyPct: 93,
    leasedPct: 95,
    toursLastWeek: 0,
    leasesLastWeek: 0,
    deposit: "$500",
    specials: "2 Months free + $1000 look-and-lease on 13M",
    freeRentWeeks: 8,
    lookAndLeaseBonus: 1000,
    amenities: ["rooftop", "pool", "gym", "lounge", "coworking"],
    threatLevel: 5,
    compQualityScore: 84,
    unitTypes: [
      { type: "studio", minRent: 2731, maxRent: 2954, avgRent: 2843, minSqft: 530, maxSqft: 534, avgSqft: 532 },
      { type: "1BR", minRent: 2808, maxRent: 3642, avgRent: 3225, minSqft: 673, maxSqft: 1309, avgSqft: 991 },
      { type: "2BR", minRent: 3630, maxRent: 4299, avgRent: 3965, minSqft: 1081, maxSqft: 1326, avgSqft: 1204 },
    ],
  },
  {
    id: "c-ava-hollywood",
    name: "Ava Hollywood",
    address: "6775 Selma Ave., LA 90028",
    phone: "888.672.3134",
    units: 248,
    distanceMiles: 0.9,
    occupancyPct: 93,
    leasedPct: 95,
    toursLastWeek: 7,
    leasesLastWeek: 0,
    amenities: ["rooftop", "pool", "gym", "lounge"],
    specials: "Up to 2 months free",
    freeRentWeeks: 8,
    threatLevel: 4,
    compQualityScore: 78,
    unitTypes: [
      { type: "studio", minRent: 2825, maxRent: 2954, avgRent: 2890, avgSqft: 532 },
      { type: "1BR", minRent: 3006, maxRent: 3509, avgRent: 3258, avgSqft: 758 },
      { type: "2BR", minRent: 3525, maxRent: 4015, avgRent: 3770, avgSqft: 2525 },
    ],
  },
  {
    id: "c-archer-hollywood",
    name: "Archer Hollywood",
    address: "6677 Santa Monica Blvd, LA 90038",
    phone: "571.789.1177",
    units: 695,
    distanceMiles: 1.1,
    occupancyPct: 96,
    leasedPct: 93,
    deposit: "$700 & up",
    specials: "1 month free + $1000 look-and-lease",
    freeRentWeeks: 4,
    lookAndLeaseBonus: 1000,
    amenities: ["rooftop", "pool", "gym", "lounge", "coworking", "parking"],
    threatLevel: 4,
    compQualityScore: 77,
    unitTypes: [
      { type: "studio", minRent: 2325, maxRent: 3250, avgRent: 2788, avgSqft: 602 },
      { type: "1BR", minRent: 2524, maxRent: 3534, avgRent: 3029, avgSqft: 779 },
      { type: "2BR", minRent: 3509, maxRent: 4709, avgRent: 4109, avgSqft: 1114 },
    ],
  },
  {
    id: "c-zen-hollywood",
    name: "Zen Hollywood",
    // Canonical leasing address per public listings; field-tour confirmed.
    address: "1825 N Las Palmas Ave, Los Angeles, CA 90028",
    alternateAddress: "1718 N Las Palmas Ave, LA 90028 (prior call-around value)",
    phone: "213-392-8076",
    units: 224,
    distanceMiles: 0.1,
    occupancyPct: 91,
    leasedPct: 91,
    deposit: "$750-1000",
    specials: "1 month free; up to 8 weeks free on 19-month lease (approved credit, select units); $1,000 look-and-lease within 72hr",
    freeRentWeeks: 8,
    lookAndLeaseBonus: 1000,
    amenities: ["rooftop","pool","gym","lounge","bar","game_room","theater","business_center","bbq_grill","valet","parking_garage","in_unit_laundry"],
    threatLevel: 5,
    compQualityScore: 88,
    unitTypes: [
      { type: "studio", minRent: 2280, maxRent: 2735, avgRent: 2508, avgSqft: 656 },
      { type: "1BR", minRent: 2200, maxRent: 2995, avgRent: 2598, avgSqft: 700 },
      { type: "2BR", minRent: 3270, maxRent: 4995, avgRent: 4123, avgSqft: 1235 },
    ],
    notes: "FIELD VERIFIED 2026-05-26 by Bailey. Right next door — premium amenity comp. Verified units: 522 ($2,995, 762 sqft, 1BR, available), 625 (not ready, $4,995, 1441 sqft, 2BR), probable 630 ($4,500, 6th floor 2BR), 2nd-floor double (~$4,000, 1229 sqft), 424 (needs verification). Water included; power/gas/internet excluded; valet + parking included (1 spot/bedroom).",
    competitorStrategicType: "premium_amenity_comp",
    competitorTags: [
      "premium_amenity_comp","field_verified","high_threat","parking_advantage",
      "concession_threat","strong_common_areas","in_unit_laundry","pool","valet",
    ],
    fieldVerified: true,
    fieldVerifiedAt: "2026-05-26",
    fieldVerifiedBy: "Bailey",
    fieldVerificationConfidence: "high",
    amenityThreatLevel: 5,
    parkingThreatLevel: 5,
    concessionThreatLevel: 5,
  },
  {
    id: "c-jardine",
    name: "Jardine",
    address: "1825 N Las Palmas Ave, LA 90028",
    phone: "310-916-7407",
    units: 118,
    distanceMiles: 0.1,
    occupancyPct: 92,
    leasedPct: 92,
    specials: "None — low vacancy. Prices subject to daily change. (Prior call-around: up to 8 weeks free + $1K LAL.)",
    freeRentWeeks: 0,
    lookAndLeaseBonus: 0,
    amenities: ["rooftop", "rooftop_pool", "gym", "theater", "garden_room", "pool_clubhouse", "security_24_7", "luxury_lobby", "coffee_offered", "scent_control", "exterior_quality"],
    // threatLevel is the OLD single-score legacy field. Smart threat system (Sprint 10) separates
    // directThreatScore (low ~1.7), tourQualityScore (high 4.5), learningScore (high 4.5).
    // Jardine is a PREMIUM ASPIRATIONAL COMP — NOT a direct pricing threat to Baxter.
    // Do NOT use Jardine as a rent anchor. Use it for leasing experience benchmarking ONLY.
    threatLevel: 2,
    compQualityScore: 83,
    competitorStrategicType: "premium_amenity_comp",
    competitorTags: ["premium_amenity_comp","field_verified","luxury_tier","low_availability","not_direct_rent_comp","scent_control","coffee_offered","premium_aspirational_comp"],
    fieldVerified: true,
    fieldVerifiedAt: "2026-05-27",
    fieldVerifiedBy: "Bailey",
    fieldVerificationConfidence: "high",
    amenityThreatLevel: 5,
    parkingThreatLevel: 3,
    concessionThreatLevel: 2,
    unitTypes: [
      // Bailey field tour 2026-05-27 — observed units.
      { type: "1BR", minRent: 3155, maxRent: 3155, avgRent: 3155, avgSqft: 583 },
      { type: "2BR", minRent: 5295, maxRent: 5295, avgRent: 5295, avgSqft: 1304 },
    ],
    notes: "Adjacent property — true comp.",
  },
  {
    id: "c-rise-hollywood",
    name: "The Rise Hollywood",
    address: "6390 De Longpre Ave",
    phone: "833-477-1389",
    units: 193,
    distanceMiles: 0.7,
    occupancyPct: 93,
    leasedPct: 93,
    specials: "Reduced pricing",
    amenities: ["rooftop", "pool", "gym", "lounge"],
    threatLevel: 3,
    compQualityScore: 70,
    unitTypes: [
      { type: "studio", avgRent: 2235, avgSqft: 482 },
      { type: "1BR", minRent: 3155, maxRent: 3695, avgRent: 3425, avgSqft: 705 },
      { type: "2BR", minRent: 5115, maxRent: 5955, avgRent: 5535, avgSqft: 1127 },
    ],
  },
  // Sprint 8 — The Highland (Bailey field tour 2026-05-27).
  {
    id: "c-highland",
    name: "The Highland",
    address: "1411 N Highland Ave, Hollywood, CA 90028",
    phone: "(323) 741-6667",
    website: "https://www.thehighlandla.com",
    units: 76,
    distanceMiles: 0.4,
    specials: "8 weeks free, applied months 2 + 4 (per flyer)",
    freeRentWeeks: 8,
    amenities: ["rooftop_pool","gym","courtyard","lounge","office_spaces","maintenance_24_7"],
    threatLevel: 4,
    compQualityScore: 76,
    competitorStrategicType: "balanced_comp",
    competitorTags: ["field_verified","nearby_amenity_comp","motel_circulation","small_bedrooms","tiny_balcony","carpet_in_bedroom","rooftop_pool"],
    fieldVerified: true,
    fieldVerifiedAt: "2026-05-27",
    fieldVerifiedBy: "Bailey",
    fieldVerificationConfidence: "high",
    amenityThreatLevel: 4,
    parkingThreatLevel: 3,
    concessionThreatLevel: 4,
    unitTypes: [
      // Bailey tour observed.
      { type: "1BR", minRent: 2870, maxRent: 2870, avgRent: 2870, avgSqft: 730 },
      { type: "2BR", minRent: 4169, maxRent: 4169, avgRent: 4169, avgSqft: 1287 },
    ],
  },
  // Sprint 8 — Actual 1600 Vine (Bailey field tour 2026-05-27).
  // NOTE: address unknown; do not invent. Display name only.
  {
    id: "c-vine-1600",
    name: "1600 Vine",
    address: "1600 Vine St, Hollywood, CA (needs verification)",
    units: 0,
    distanceMiles: undefined,
    specials: "Not disclosed during tour.",
    amenities: ["pool","concierge","in_unit_laundry"],
    threatLevel: 4,
    compQualityScore: 72,
    competitorStrategicType: "premium_amenity_comp",
    competitorTags: ["field_verified","poor_service","large_2br","two_story_unit","huge_closets","concierge"],
    fieldVerified: true,
    fieldVerifiedAt: "2026-05-27",
    fieldVerifiedBy: "Bailey",
    fieldVerificationConfidence: "high",
    amenityThreatLevel: 4,
    parkingThreatLevel: 3,
    concessionThreatLevel: 2,
    unitTypes: [
      // Bailey tour: 5th floor 2BR / 2.5BA — unit number unknown.
      { type: "2BR", minRent: 5200, maxRent: 5200, avgRent: 5200, avgSqft: 2178 },
    ],
  },
  {
    id: "c-ardence-bloom",
    name: "Ardence & Bloom",
    address: "1331 N Cahuenga Blvd",
    phone: "213-577-2487",
    units: 300,
    distanceMiles: 0.6,
    occupancyPct: 92,
    leasedPct: 93,
    specials: "1 month free + $500 look-and-lease",
    freeRentWeeks: 4,
    lookAndLeaseBonus: 500,
    amenities: ["rooftop", "pool", "gym", "lounge", "coworking"],
    threatLevel: 3,
    compQualityScore: 72,
    unitTypes: [
      { type: "studio", avgRent: 2214, avgSqft: 520 },
      { type: "1BR", minRent: 2896, maxRent: 3658, avgRent: 3277, avgSqft: 755 },
      { type: "2BR", minRent: 3799, maxRent: 10500, avgRent: 7150, avgSqft: 1564 },
    ],
  },
  {
    id: "c-hanover-hollywood",
    name: "Hanover Hollywood",
    address: "6200 W Sunset Blvd",
    phone: "747-307-5779",
    units: 270,
    distanceMiles: 0.9,
    occupancyPct: 88,
    leasedPct: 92,
    toursLastWeek: 12,
    leasesLastWeek: 10,
    specials: "6 weeks free + 1 add'l week if move in by 5/31",
    freeRentWeeks: 7,
    amenities: ["rooftop", "pool", "gym", "lounge", "coworking", "parking"],
    threatLevel: 5,
    compQualityScore: 85,
    unitTypes: [
      { type: "studio", minRent: 2085, maxRent: 2200, avgRent: 2143, avgSqft: 611 },
      { type: "1BR", minRent: 2580, maxRent: 3074, avgRent: 2827, avgSqft: 751 },
      { type: "2BR", minRent: 3038, maxRent: 4038, avgRent: 3538, avgSqft: 1062 },
    ],
    notes: "12 tours / 10 leases last week — currently winning the lease-up race.",
  },
];

export const COMPETITORS: CompetitorProperty[] = RAW_COMPETITORS.map(withVerificationDefaults);

// --- Marketing channels (from meeting transcript) ---
export const MARKETING_SOURCES: MarketingSource[] = [
  {
    id: "ms-apartments",
    name: "Apartments.com",
    monthlyCost: 6500,
    leads: 1,
    tours: 1,
    applications: 0,
    leases: 0,
    notes: "1 of 8 recent leads. ~$1,000/unit/month for top-tier listing. Saturated market (~80 properties at top tier).",
    recommendation: "Cut tier or pause. ROI is poor at current lead volume.",
  },
  {
    id: "ms-zumper",
    name: "Zumper (AppFolio feed)",
    monthlyCost: 0,
    leads: 7,
    tours: 2,
    applications: 0,
    leases: 0,
    notes: "Free via AppFolio. Driving 7 of 8 recent leads.",
    recommendation: "Confirm AppFolio sync; consider paid boost.",
  },
  {
    id: "ms-craigslist",
    name: "Craigslist",
    monthlyCost: 30,
    leads: 0,
    tours: 0,
    applications: 0,
    leases: 0,
    notes: "Catherine raised reactivating. Historical channel for SGD.",
    recommendation: "Restart immediately — test 4 weeks.",
  },
  {
    id: "ms-website",
    name: "Website",
    monthlyCost: 200,
    leads: 0,
    tours: 0,
    applications: 0,
    leases: 0,
    notes: "Old website inherited from previous owner. Transfer in progress.",
    recommendation: "Migrate. Add booking widget.",
  },
  {
    id: "ms-instagram",
    name: "Instagram",
    monthlyCost: 0,
    leads: 0,
    tours: 0,
    applications: 0,
    leases: 0,
    recommendation: "Set up content calendar. Free.",
  },
];

// --- Leads (illustrative — replace with AppFolio export) ---
export const LEADS: Lead[] = [
  { id: "l-1", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-20", stage: "toured", unitOfInterest: "308" },
  { id: "l-2", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-21", stage: "contacted" },
  { id: "l-3", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-22", stage: "lead" },
  { id: "l-4", source: "Apartments.com", receivedDate: "2026-05-22", stage: "lost", lostReason: "Better competitor concession" },
  { id: "l-5", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-23", stage: "lead" },
  { id: "l-6", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-24", stage: "tour_scheduled", unitOfInterest: "301" },
  { id: "l-7", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-25", stage: "lead" },
  { id: "l-8", source: "Zumper (AppFolio feed)", receivedDate: "2026-05-26", stage: "contacted" },
];

// --- Tenants — recertification queue (illustrative) ---
/**
 * Sprint 7 — bundle-safe tenant aggregate only.
 *
 * Sensitive fields (real name, income, LAHD cap detail, private notes, health-related
 * notes, contact info) moved to Supabase tables `tenants` + `tenant_private_details`
 * with role-restricted RLS (admin/manager only on private_details).
 *
 * This array exists only so existing static UI keeps rendering without crashing while
 * the tenant outreach / recertification pages migrate to Supabase reads. Aggregate
 * status only — NO names, NO income, NO LAHD detail, NO private notes.
 */
export const TENANTS: Tenant[] = [
  {
    id: "t-yolanda",
    name: "Affordable-unit escalation #1",
    unitNumber: "—",
    program: "section8",
    subsidyProvider: "HACLA",
    status: "escalation",
    documentsRequested: [],
    documentsReceived: [],
    contactAttempts: 0,
    riskLevel: "high",
    notes: "Sensitive details in Supabase (tenant_private_details). Admin/Manager only.",
    assignedStaff: "Catherine",
  },
  {
    id: "t-francina",
    name: "Tenant 2",
    unitNumber: "—",
    program: "section8",
    subsidyProvider: "HACLA",
    status: "all_docs",
    documentsRequested: [],
    documentsReceived: [],
    contactAttempts: 0,
    riskLevel: "low",
    assignedStaff: "Catherine",
  },
  {
    id: "t-charlotte",
    name: "Brilliant Corners candidate",
    unitNumber: "—",
    program: "brilliant_corners",
    subsidyProvider: "Brilliant Corners",
    status: "docs_requested",
    documentsRequested: [],
    documentsReceived: [],
    contactAttempts: 0,
    riskLevel: "medium",
    assignedStaff: "Joanna",
  },
  {
    id: "t-summer",
    name: "Tenant 4",
    unitNumber: "—",
    program: "conventional",
    status: "not_started",
    documentsRequested: [],
    documentsReceived: [],
    contactAttempts: 0,
    riskLevel: "medium",
    assignedStaff: "Joanna",
  },
];

// --- Walkthrough campaign tours (priority list) ---
export const WALKTHROUGH_TOURS: WalkthroughTour[] = [
  { id: "w-1", competitorId: "c-zen-hollywood", assignedTo: "Bailey", status: "queued", priority: 5, persona: "1BR seeker, $2,800 budget, move-in 30 days" },
  { id: "w-2", competitorId: "c-jardine", assignedTo: "Shane", status: "queued", priority: 5, persona: "Same as above" },
  { id: "w-3", competitorId: "c-line-lofts", assignedTo: "Bailey", status: "queued", priority: 4 },
  { id: "w-4", competitorId: "c-jefferson-highland", assignedTo: "Shane", status: "called", priority: 5 },
  { id: "w-5", competitorId: "c-camden", assignedTo: "Bailey", status: "queued", priority: 5 },
  { id: "w-6", competitorId: "c-modera-hollywood", assignedTo: "Shane", status: "queued", priority: 4 },
  { id: "w-7", competitorId: "c-hanover-hollywood", assignedTo: "Bailey", status: "queued", priority: 5 },
  { id: "w-8", competitorId: "c-fusion", assignedTo: "Shane", status: "queued", priority: 3 },
];

// --- Tasks ---
export const TASKS: Task[] = [
  { id: "tk-1", title: "Tour Zen Hollywood + Jardine (adjacent)", category: "walkthrough", owner: "Bailey", priority: 5, status: "open", relatedCompetitorId: "c-zen-hollywood" },
  { id: "tk-2", title: "Cut Apartments.com tier or pause", category: "marketing", owner: "Evan", priority: 4, status: "open" },
  { id: "tk-3", title: "Reactivate Craigslist listings", category: "marketing", owner: "Lucas", priority: 4, status: "open" },
  { id: "tk-4", title: "Submit LAHD utility allowance forms to Urban", category: "lahd", owner: "Catherine", priority: 5, status: "in_progress" },
  { id: "tk-5", title: "Escalated affordable-unit case — schedule HACLA move conversation", category: "hacla", owner: "Joanna", priority: 5, status: "in_progress", relatedTenantId: "t-yolanda" },
  { id: "tk-6", title: "Migrate inherited Baxter website", category: "marketing", owner: "Bailey", priority: 3, status: "open" },
  { id: "tk-7", title: "Reupholster rooftop lounge chairs (Catherine sourcing fabric)", category: "data_cleanup", owner: "Catherine", priority: 2, status: "open" },
  { id: "tk-8", title: "Fill Brilliant Corners affordable unit", category: "recertification", owner: "Joanna", priority: 4, status: "open", relatedTenantId: "t-charlotte" },
  // Sprint 3 — Zen field-tour follow-ups
  { id: "tk-zen-424", title: "Verify Zen Unit 424 rent/sqft/layout", category: "market_comp", owner: "Bailey", priority: 5, status: "open", relatedCompetitorId: "c-zen-hollywood" },
  { id: "tk-zen-630", title: "Verify Zen Unit 630 exact sqft and concession", category: "market_comp", owner: "Bailey", priority: 5, status: "open", relatedCompetitorId: "c-zen-hollywood" },
  { id: "tk-zen-19m", title: "Confirm Zen 19-month special applicability by unit", category: "market_comp", owner: "Bailey", priority: 4, status: "open", relatedCompetitorId: "c-zen-hollywood" },
  { id: "tk-zen-photos", title: "Upload/attach full Zen field-tour photo batch (42 .heic → /public/zen-tour/)", category: "data_cleanup", owner: "Bailey", priority: 5, status: "open", relatedCompetitorId: "c-zen-hollywood" },
  { id: "tk-zen-baxter-1br", title: "Compare Baxter 1BRs against Zen Unit 522", category: "pricing", owner: "Bailey", priority: 5, status: "open", relatedCompetitorId: "c-zen-hollywood" },
];

export const DEFAULT_MATCHING_WEIGHTS: MatchingWeights = {
  bedrooms: 0.20,
  sqft: 0.20,
  distance: 0.15,
  amenities: 0.15,
  buildingClass: 0.15,
  concessions: 0.10,
  qualitative: 0.05,
};

export const UTILITY_ALLOWANCE_SCHEDULE = {
  studio: 165,
  oneBR: 206,
  twoBR: 248,
};

// LAHD covenant cap on (tenant rent + utility allowance), by unit size — placeholder, edit in /utility-allowance
export const LAHD_CAPS = {
  studio: 900,
  oneBR: 1000,
  twoBR: 1200,
};

// --- Local partnership seeds ---
// IMPORTANT: status is always "needs_research". Contacts, emails, and phone numbers
// are intentionally blank — Claude does NOT invent names. Bailey must verify.
const NOW = new Date().toISOString();
const partnership = (
  id: string,
  entityType: LocalPartnership["entityType"],
  name: string,
  partnershipIdea: LocalPartnership["partnershipIdea"],
  leadPotentialScore: number,
  notes?: string,
): LocalPartnership => ({
  id,
  entityType,
  name,
  partnershipIdea,
  leadPotentialScore,
  confidence: "needs_research",
  status: "not_contacted",
  notes: notes ? `${notes} · Contact not verified. Research before outreach.` : "Contact not verified. Research before outreach.",
  createdAt: NOW,
  updatedAt: NOW,
});

export const LOCAL_PARTNERSHIPS_SEED: LocalPartnership[] = [
  partnership("lp-hollywood-pres", "hospital", "Hollywood Presbyterian Medical Center", "employee_housing_resource", 5, "Major employer ~0.5mi from Baxter. Nursing staff turnover = housing demand."),
  partnership("lp-childrens", "hospital", "Children's Hospital Los Angeles", "employee_housing_resource", 4, "~1mi east. Residency/nursing housing relocation pipeline."),
  partnership("lp-amda", "performing_arts_school", "AMDA College of the Performing Arts", "student_housing_resource", 5, "Adjacent campus. Student housing fairs are the target."),
  partnership("lp-la-film-school", "film_school", "The Los Angeles Film School", "student_housing_resource", 5, "0.4mi away. Student housing resource board."),
  partnership("lp-stella-adler", "performing_arts_school", "Stella Adler Academy of Acting & Theatre", "student_housing_resource", 3),
  partnership("lp-paramount", "production_studio", "Paramount Pictures (production housing lead source)", "corporate_housing", 4, "Production crews on short-term assignments — corporate housing pitch."),
  partnership("lp-netflix", "entertainment_employer", "Netflix (Hollywood office, employee relocation)", "relocation_referral", 4, "Relocation team contact — research before outreach."),
  partnership("lp-loews", "hospitality_employer", "Loews Hollywood Hotel", "preferred_employer_discount", 3, "Hospitality staff housing pipeline."),
  partnership("lp-roosevelt", "hospitality_employer", "The Hollywood Roosevelt", "preferred_employer_discount", 3),
  partnership("lp-corp-housing", "corporate_housing", "Local corporate-housing referral broker (TBD)", "corporate_housing", 4, "Identify specific broker before outreach."),
];

