-- Auto-generated by upload-zen-photos-to-supabase.sh
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/01-img_2251.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/01-img_2251.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 1;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/02-img_2252.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/02-img_2252.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 2;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/03-img_2253.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/03-img_2253.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 3;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/04-img_2254.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/04-img_2254.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 4;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/05-img_2255.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/05-img_2255.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 5;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/06-img_2256.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/06-img_2256.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 6;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/07-img_2257.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/07-img_2257.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 7;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/08-img_2258.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/08-img_2258.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 8;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/09-img_2259.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/09-img_2259.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 9;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/10-img_2260.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/10-img_2260.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 10;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/11-img_2261.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/11-img_2261.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 11;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/12-img_2262.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/12-img_2262.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 12;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/13-img_2263.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/13-img_2263.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 13;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/14-img_2264.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/14-img_2264.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 14;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/15-img_2265.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/15-img_2265.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 15;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/16-img_2266.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/16-img_2266.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 16;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/17-img_2267.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/17-img_2267.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 17;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/18-img_2268.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/18-img_2268.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 18;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/19-img_2269.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/19-img_2269.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 19;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/20-img_2270.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/20-img_2270.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 20;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/21-img_2271.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/21-img_2271.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 21;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/22-img_2272.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/22-img_2272.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 22;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/23-img_2273.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/23-img_2273.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 23;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/24-img_2274.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/24-img_2274.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 24;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/25-img_2275.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/25-img_2275.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 25;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/26-img_2276.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/26-img_2276.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 26;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/27-img_2277.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/27-img_2277.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 27;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/28-img_2278.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/28-img_2278.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 28;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/29-img_2279.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/29-img_2279.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 29;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/30-img_2280.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/30-img_2280.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 30;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/31-img_2281.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/31-img_2281.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 31;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/32-img_2282.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/32-img_2282.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 32;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/33-img_2283.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/33-img_2283.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 33;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/34-img_2284.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/34-img_2284.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 34;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/35-img_2285.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/35-img_2285.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 35;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/36-img_2286.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/36-img_2286.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 36;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/37-img_2287.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/37-img_2287.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 37;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/38-img_2288.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/38-img_2288.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 38;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/39-img_2289.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/39-img_2289.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 39;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/40-img_2290.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/40-img_2290.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 40;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/41-img_2293.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/41-img_2293.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 41;
update public.photo_evidence
   set storage_path = 'competitors/zen-hollywood/field-tour-2026-05-26/42-img_2294.jpg',
       public_url = 'https://yxeechpebbuddonseldu.supabase.co/storage/v1/object/public/baxter-ops-photos/competitors/zen-hollywood/field-tour-2026-05-26/42-img_2294.jpg',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = 42;
