#!/usr/bin/env bash
# Upload converted Zen .jpg files to Supabase Storage bucket baxter-ops-photos.
#
# Reads NEXT_PUBLIC_SUPABASE_URL + NEXT_PUBLIC_SUPABASE_ANON_KEY from .env.local
# (which the dev server reads anyway). Uses curl against the Storage REST API.
#
# Path convention:
#   competitors/zen-hollywood/field-tour-2026-05-26/<photoOrder>-<filenameStemLower>.jpg
#
# After upload, this script updates photo_evidence rows with storage_path and public_url
# via a SQL file you can run from MCP (or copy into Supabase SQL editor).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"
SRC="$ROOT/public/zen-tour/converted"
BUCKET="baxter-ops-photos"
PREFIX="competitors/zen-hollywood/field-tour-2026-05-26"
UPDATE_SQL="$ROOT/scripts/_zen-photo-url-updates.sql"

# load env
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE" >&2; exit 1
fi
# shellcheck disable=SC1090
export $(grep -E "^NEXT_PUBLIC_SUPABASE_(URL|ANON_KEY)=" "$ENV_FILE" | xargs)

if [[ -z "${NEXT_PUBLIC_SUPABASE_URL:-}" || -z "${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}" ]]; then
  echo "NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY not set." >&2; exit 1
fi

if [[ ! -d "$SRC" ]]; then
  echo "Converted directory not found: $SRC. Run convert-zen-heic-to-jpg.sh first." >&2; exit 1
fi

# Build deterministic photo_order list. IMG_2251 → 1, IMG_2294 → 42 with 2291/2292 absent.
declare -a FILES=(
  IMG_2251 IMG_2252 IMG_2253 IMG_2254 IMG_2255 IMG_2256 IMG_2257 IMG_2258 IMG_2259 IMG_2260
  IMG_2261 IMG_2262 IMG_2263 IMG_2264 IMG_2265 IMG_2266 IMG_2267 IMG_2268 IMG_2269 IMG_2270
  IMG_2271 IMG_2272 IMG_2273 IMG_2274 IMG_2275 IMG_2276 IMG_2277 IMG_2278 IMG_2279 IMG_2280
  IMG_2281 IMG_2282 IMG_2283 IMG_2284 IMG_2285 IMG_2286 IMG_2287 IMG_2288 IMG_2289 IMG_2290
  IMG_2293 IMG_2294
)

: > "$UPDATE_SQL"
echo "-- Auto-generated by upload-zen-photos-to-supabase.sh" >> "$UPDATE_SQL"

ok=0; fail=0
for i in "${!FILES[@]}"; do
  order=$((i + 1))
  stem="${FILES[$i]}"
  src_file="$SRC/${stem}.jpg"
  stem_lower="$(printf '%s' "$stem" | tr '[:upper:]' '[:lower:]')"
  remote_key="${PREFIX}/$(printf '%02d' "$order")-${stem_lower}.jpg"
  if [[ ! -f "$src_file" ]]; then
    echo "MISS (no source): $src_file"; fail=$((fail+1)); continue
  fi

  # POST to upload (use PUT to overwrite if exists)
  http_code=$(curl -s -o /tmp/zen-upload.body -w "%{http_code}" \
    -X POST "$NEXT_PUBLIC_SUPABASE_URL/storage/v1/object/$BUCKET/$remote_key" \
    -H "apikey: $NEXT_PUBLIC_SUPABASE_ANON_KEY" \
    -H "Authorization: Bearer $NEXT_PUBLIC_SUPABASE_ANON_KEY" \
    -H "x-upsert: true" \
    -H "Content-Type: image/jpeg" \
    --data-binary "@$src_file" || true)

  if [[ "$http_code" =~ ^2 ]]; then
    public_url="$NEXT_PUBLIC_SUPABASE_URL/storage/v1/object/public/$BUCKET/$remote_key"
    ok=$((ok+1))
    printf "ok (%s): order=%d  %s\n" "$http_code" "$order" "$remote_key"
    cat >> "$UPDATE_SQL" <<SQL
update public.photo_evidence
   set storage_path = '${remote_key}',
       public_url = '${public_url}',
       updated_at = now()
 where collection_id = 'zen-field-tour-2026-05-26' and photo_order = ${order};
SQL
  else
    fail=$((fail+1))
    body="$(cat /tmp/zen-upload.body 2>/dev/null || true)"
    echo "FAIL ($http_code): order=$order  $remote_key  body=$body"
  fi
done

echo
echo "Done. ok=$ok fail=$fail. SQL updates written to: $UPDATE_SQL"
echo "Now run that SQL against Supabase (via MCP execute_sql, psql, or the Supabase SQL editor)."
